### ISSUE TITLE
Can u show examples for custom data

### ISSUE THREAD

**Issue by batman-do** [ariecattan/multi_mds#1]
Hey guys, I excited in your paper <3

Can u share custom data for train, val, test and how to inference with test data only have multi-documents ?

Thanks guys !

**Comment by ariecattan** [comment]
Hi @Dean98AI,

I'm not sure I got your question, do you mean examples of MDS topics with a few degree of merging or do you refer to the experiments in Table 4? Could you clarify please?

Best
