### ISSUE TITLE
Please provide a jsonl file of source documents and the summary

### ISSUE THREAD

**Issue by SleepyLan** [ariecattan/multi_mds#2]
Hello,

Thank you for creating this amazing project! I've been trying to use it but have run into some issues, and I was hoping you could provide some assistance.

I followed the instructions in the README, but I encountered errors when preparing for the jsonl file of this part.

<img width="848" alt="截屏2024-04-23 21 32 20" src="https://github.com/ariecattan/multi_mds/assets/80094106/93da0b8c-a09e-433e-b0bb-e4eae800ba5c">

I input a simple jsonl file as following:

`{"document": ["The quick brown fox jumps over the lazy dog. The dog, startled by the fox's sudden movement, wakes up and starts chasing the fox. The fox, being quick and agile, easily outmaneuvers the dog and escapes into the nearby forest."], "summary": ["A quick brown fox jumps over a lazy dog, waking it up. The dog chases the fox, but the fox escapes into the forest."], "topic_id": "1"}
{"document": ["In a distant galaxy, there exists a planet named Zephyria. The inhabitants of Zephyria are known as Zephyrians, and they possess advanced technology that allows them to travel across the stars. One day, a group of Zephyrian explorers discovers a new planet with signs of intelligent life."], "summary": ["Zephyrians, an advanced alien race from planet Zephyria, discover a new planet with intelligent life during their space exploration."], "topic_id": "2"}
{"document": ["The Eiffel Tower is an iconic landmark located in Paris, France. It was designed by Gustave Eiffel and completed in 1889. The tower stands at a height of 324 meters (1,063 feet) and consists of three levels accessible to visitors. The Eiffel Tower attracts millions of tourists every year and offers stunning views of the city."], "summary": ["The Eiffel Tower, an iconic Parisian landmark designed by Gustave Eiffel, was completed in 1889. It stands 324 meters tall, has three accessible levels, and attracts millions of visitors annually with its stunning city views."], "topic_id": "3"}`

And I receive an error:
`ValueError: [E866] Expected a string or 'Doc' as input, but got: <class 'list'>.`

Would it be possible for you to provide a complete, runnable example of jsonl file?

If you need more information about the specific problems I've encountered, please let me know, and I'll do my best to provide more details.

Thank you again for your hard work and assistance!

Best regards

**Comment by ariecattan** [comment]
Thanks for your interests in our project. 

There was a mistake in the documentation, the field `summary` is supposed to be a `string` and not a `list` (I've just fixed the README). You can also find an example file in the repo.

**Comment by SleepyLan** [comment]
Thank you for your help! I've checked the updated documentation and example file.
I appreciate you for resolving my issue.

**Comment by SleepyLan** [comment]
Thank you for your help! I've checked the updated documentation and example file.
I appreciate you for resolving my issue.
